### ISSUE TITLE
Оцифрування білетів 2021

### ISSUE THREAD

**Issue by skalinets** [Scheepsjongen/scheepsjongen.github.io#11]
Привіт! Вчора знайшов цю репу в процесі підготовки до іспитів, дякую за іі створення 🙂. Побачив ініціативу щодо оновлення питань за 2021 рік. 
Я пишу скрипт, що має конвертнути Google doc в xml (усі 600+ питань за раз). Він вже на 80% готовий, вже всі питання розбираються, лишилося сформувати xml. У вівторок планую зробити пул ріквест, до того часу я буду офлайн. Буде текст, малюнки ще не парсив, але не думаю, що будуть проблеми.

**Comment by Olezha** [comment]
Привіт! Це буде чудово. 1-170 я додав вручну :monkey: з виправленням помилок розпізнання - думаю не варто їх міняти. Залишилось дуже багато і такий скрипт буде просто знахідка.
Заздалегідь дякую!

**Comment by Olezha** [comment]
Супер, я вже приймаю ці правки. Лише одне зауваження: новий тест (xml тесту) знаходиться в файлі `quiz/test.xml` а в файлі `quiz/pre-2021-test.xml` знаходиться старий тест (вирішив і його лишити). Пліс, перекинь правки в `quiz/test.xml`.

**Comment by Olezha** [comment]
Загалом працює, думаю можна вже тренуватись. Залишились малюнки, форматування, виправлення помилок розпізнання, але думаю це інші задачі і по бажанню. Малюнки я днями думаю додам вручну це вже порядком легше.
Дуже дякую!
